// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ifecepxptvfrjmexwyqn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlmZWNlcHhwdHZmcmptZXh3eXFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NDc2MDcsImV4cCI6MjA2NTIyMzYwN30.G-NW7cVR6Gk_jAikLqRh6gEH23yGt9w3Kaudl6aajFw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);